name: iOS Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload-ios:
    name: Upload iOS App
    runs-on: macos-latest

    steps:
    # 1️⃣ Забираем код
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Подготавливаем App Store Connect API ключ
    - name: Prepare App Store Connect API key
      run: |
        mkdir -p fastlane
        echo ${{ secrets.APP_STORE_CONNECT_API_KEY_FILE_BASE64 }} | base64 --decode > fastlane/AuthKey_QMN99784M3.p8

    # 3️⃣ Устанавливаем Fastlane
    - name: Install fastlane
      run: sudo gem install fastlane

    # 4️⃣ Загружаем готовый IPA в App Store Connect
    - name: Upload IPA to App Store Connect
      working-directory: ./fastlane   # Fastfile должен быть здесь
      run: fastlane ios upload
      env:
        APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
        APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        FASTLANE_SKIP_UPDATE_CHECK: 1
