name: iOS Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload-ios:
    name: Upload iOS App
    runs-on: macos-latest

    steps:
    # 1️⃣ Забираем код
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Подготавливаем App Store Connect API ключ
    - name: Prepare App Store Connect API key
      run: |
        mkdir -p fastlane
        echo ${{ secrets.APP_STORE_CONNECT_API_KEY_FILE_BASE64 }} | base64 --decode > fastlane/AuthKey_QMN99784M3.p8

    # 3️⃣ Устанавливаем Fastlane
    - name: Install fastlane
      run: sudo gem install fastlane

    - name: Check if IPA exists
      run: |
        ls ./plantmama_flutter/build/ios/ipa/
        if [ ! -f ./build/ios/ipa/plantmana_test.ipa ]; then
          echo "IPA file does not exist!"
          exit 1
        fi

    # 4️⃣ Указываем путь к вашему IPA и загружаем его в App Store Connect
    - name: Upload IPA to App Store Connect
      run: |
        fastlane deliver --ipa ./build/ios/ipa/plantmana_test.ipa --skip_binary_upload true
      env:
        APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
        APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        FASTLANE_SKIP_UPDATE_CHECK: 1
